#pragma once

#include "Toybox/Core/IncGuards.h"
#include "Toybox/Core/ToyboxDefs.h"

THIRD_PARTY_GUARDS_BEGIN
#include <Urho3D/Core/Context.h>
#include <Urho3D/Input/InputEvents.h>
THIRD_PARTY_GUARDS_END


///  Default keys for each controller
enum : int
{
    KEY_VEHICLE_STRAFE_INC = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_STRAFE_DEC = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_STRAFE_MAX = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_STRAFE_STOP = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_PITCH_UP = Urho3D::KEY_W,
    KEY_VEHICLE_PITCH_DOWN = Urho3D::KEY_S,

    KEY_VEHICLE_UP_INC = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_UP_DEC = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_UP_MAX = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_UP_STOP = Urho3D::KEY_UNKNOWN,
    KEY_VEHICLE_YAW_LEFT = Urho3D::KEY_A,
    KEY_VEHICLE_YAW_RIGHT = Urho3D::KEY_D,

    KEY_VEHICLE_FORWARD_INC = Urho3D::KEY_KP_PLUS,
    KEY_VEHICLE_FORWARD_DEC = Urho3D::KEY_KP_MINUS,
    KEY_VEHICLE_FORWARD_MAX = Urho3D::KEY_TAB,
    KEY_VEHICLE_FORWARD_STOP = Urho3D::KEY_BACKSPACE,
    KEY_VEHICLE_ROLL_LEFT = Urho3D::KEY_Q,
    KEY_VEHICLE_ROLL_RIGHT = Urho3D::KEY_E,

    KEY_CHARACTER_FORWARD = Urho3D::KEY_W,
    KEY_CHARACTER_BACKWARD = Urho3D::KEY_S,
    KEY_CHARACTER_STRAFE_LEFT = Urho3D::KEY_Q,
    KEY_CHARACTER_STRAFE_RIGHT = Urho3D::KEY_E,
    KEY_CHARACTER_TURN_LEFT = Urho3D::KEY_A,
    KEY_CHARACTER_TURN_RIGHT = Urho3D::KEY_D,
    KEY_CHARACTER_JUMP = Urho3D::KEY_SPACE,
    KEY_CHARACTER_WALK = Urho3D::KEY_SHIFT,
    KEY_CHARACTER_CROUCH = Urho3D::KEY_CTRL,

	KEY_CAMERA_FORWARD = Urho3D::KEY_I,
    KEY_CAMERA_BACKWARD = Urho3D::KEY_K,
    KEY_CAMERA_PAN_LEFT = Urho3D::KEY_J,
    KEY_CAMERA_PAN_RIGHT = Urho3D::KEY_L,
    KEY_CAMERA_ROLL_LEFT = Urho3D::KEY_U,
    KEY_CAMERA_ROLL_RIGHT = Urho3D::KEY_O
};


//  Settings - DEBUG -
const bool DRAW_DEBUG_GEOMETRY = false;
const unsigned CHAR_CONTROLLER = Toybox::CHAR_CONTROLLER_KINEMATIC;
